id: PE1441BB0
initial_creation_type: input
source_metadata:
  title: Dzogchen Series
  language: en
  description: 'The following texts are available as part of our Dzogchen (rdzogs
    chen) or Great Perfection series:'
  volume:
    42ceed2718d74fcb90820673e7f86668:
      title: Advice for Hor Özer
      parent: Advice
    7f49598705ef434485bffa0ab5a94651:
      title: Advice for Palseng
      parent: Advice
    bc6f5d31146a4c1d955631e0be7dab9c:
      title: Memorandum on the Subject of Mahāmudrā and Dzogchen Instructions
      parent: Advice
    4ae95e81316347b9bdfe95f1e91e8675:
      title: Advice for Garje Khamtrul Rinpoche
      parent: Advice
    d855790aeda84bfc832da86b5a6bc9b8:
      title: Advice on Recognizing the Nature of Mind
      parent: Advice
    856a0103ed374a95b3d6804042810d49:
      title: 'Advice: Emptying the Three Realms of Existence'
      parent: Advice
    2d6370cc53f247e5841a9e9bb5e296b4:
      title: An Instruction on the Great Perfection
      parent: Advice
    2d39a656325448a09021d1ad9cf08ab0:
      title: Brief Dzogchen Instruction
      parent: Advice
    0666bedf96b141f7919c3f61bb73b163:
      title: Direct Instruction
      parent: Advice
    d0a674a4beb9446aaa458c327fe1b523:
      title: Summary of the Key Points of Advice on Trekchö
      parent: Advice
    76ecff944f3e4285bb9512088cb15bb2:
      title: Vajra Verses on the Natural State
      parent: Advice
    d107c17735f64718bf3643e7648677d4:
      title: Advice for a King
      parent: Advice
    23365ef33f1c43059753346c86022f8f:
      title: A Song of Advice for Gok Zangden
      parent: Advice
    e8e7d498d63d41089765df02a8485807:
      title: A Song to Introduce the Unmistaken View of the Great Perfection
      parent: Advice
    63acff76f2aa462a84272bc000c58cd2:
      title: 'Naturally Liberating Whatever You Meet: A Concise Instruction for Realizing
        the Nature of Mind'
      parent: Advice
    3178684b4a83449481baa5962cb0fdc8:
      title: Verses to Remove Hindrances and Sustain Realization of the Nature of
        Mind
      parent: Advice
    fd21d16083324f3ba42a3b714d76bd64:
      title: 'Vomiting Gold: A Pith Instruction in the Form of Advice for the Diligent
        Practitioner, the Excellent Atsang'
      parent: Advice
    60bac2f088a347bab29140b51ad996a3:
      title: A Liberating Reminder
      parent: Advice
    19cd5020befa4739ba8931da026966da:
      title: 'A Mirror Revealing the Crucial Points: Advice on the Ultimate Meaning'
      parent: Advice
    f1b893717552444bbfe10c0ec7cafc55:
      title: 'A Wish-Fulfilling Gem: Guidance on the Meaning of Being at Ease with
        Illusion, A Dzogchen Teaching'
      parent: Advice
    1d26a7950f0749199b998ab3e0e8d382:
      title: 'From ''Finding Comfort and Ease in Meditation'': A Guide to Locations
        for Cultivating Samadhi'
      parent: Advice
    c07d979b2431418ea2efd8ac5229389c:
      title: 'From ''Finding Comfort and Ease in Meditation'': The Practitioner of
        Meditation'
      parent: Advice
    de7c40cc903b4d9fa0f0f4f88be8a817:
      title: 'A Lamp to Dispel Darkness: An Instruction that Points Directly to the
        Very Essence of Mind in the Tradition of ‘the Old Realized Ones’'
      parent: Advice
    5cd7193044524843a4d4015446572b60:
      title: Pith Instruction on the Three Crucial Statements
      parent: Advice
    14a62e097ba84641bd07559f0881b870:
      title: The Essence of Mind
      parent: Advice
    42530b44e6c94b9ab55e62a5b7988285:
      title: 'The Essence of Wisdom: How to Sustain the Face of Rigpa'
      parent: Advice
    a7de0014641640eaab8269d78f4e48d4:
      title: The Key Points of Trekchö
      parent: Advice
    2558a43b6a7f472694f496985b803f9f:
      title: The Nature of Mind
      parent: Advice
    f12404839a4b4f1a97472b628ac4aa5a:
      title: Advice on the View, Meditation, Action and Fruition
      parent: Advice
    5495c5c1dfe64355bf9507bd5f1671f3:
      title: The Pointing-the-Staff Instruction
      parent: Advice
    362af5e6407346ebb3ba322c3d7d703a:
      title: Advice in a Single Statement (from Khenpo Ngawang Palzang)
      parent: Advice
    08223f9199584816bf84c1981aa38ca2:
      title: Principles of the Dzogchen Practice of Khordé Rushen
      parent: Advice
    abcec96810874e6da173cb1e9f067bc1:
      title: The Five Wisdoms
      parent: Advice
    974b1cb8e342413bbc7e4f7c419ef596:
      title: Advice on How to Put the Meaning of the Natural Great Perfection into
        Practice
      parent: Advice
    d231426e3cd84266ae5df27b1b8e7f10:
      title: 'Self-Liberating Meditation: A Profound Method for Attaining Enlightenment
        according to the Ultimate Great Perfection'
      parent: Advice
    72048b3c4c804ab6b0863c54a0a86484:
      title: Advice from the Lips of Tertön Sogyal
      parent: Advice
    87f0ae31db6044f19ebaa8cba38f5ca1:
      title: A Torch to Illuminate Crucial Points of the Path of Meditation
      parent: Advice
    b3bfbc50a47c4c0d990cb3c093b98042:
      title: The Four Uncommon Samayas of the Great Perfection
      parent: Advice
    24e17c2f3fab49a689245ad39ca1f4bb:
      title: A Brief Presentation of View, Meditation and Action
      parent: Advice
    6aac32079ab54822b179f3c4d78d9fff:
      title: From the Oral Tradition of the Lama of Nyarong
      parent: Advice
    82350292958f41529ac7fbcd7a8ef695:
      title: On the Final Words of Orgyen Tendzin Norbu
      parent: Commentaries
    b62ae566396c4fab874bff7aa57feae8:
      title: 'The Precious Jewelled Key: A Synopsis of the Aspiration of the Great
        Perfection Mañjuśrī'
      parent: Commentaries
    fe30014c5c4144faba191d997e3c4800:
      title: 'The Prayer of the Ground, Path & Fruition from the Heart-Essence of
        the Vast Expanse:'
      parent: Commentaries
    a3da26d9a9794be58f8dbbfc7e721567:
      title: Commentary on Vajra Verses on the Natural State
      parent: Commentaries
    4b527b067e664346a862d02c1c4801c2:
      title: Prayer to the Gurus of the Dzogchen Lineage
      parent: Lineage Prayers
    8caef6b5721e42ec8ee89e3cb36effd3:
      title: A Prayer to Shower Down the Rain of Wisdom
      parent: Lineage Prayers
    fd5afc12f07b4610b9b41be333095574:
      title: How to Count the Four Permutations of Actual and Basis
      parent: Notes
    369ad0cad1a54975a63327fe03f932cb:
      title: Commentary on Some Terms from the Great Perfection
      parent: Notes
    3b277eb0e89043a198f9cca9662b8ee5:
      title: Brief Explanation of Clarification and Transcendental Resolution from
        the Oral Tradition of Nyala Sogyal
      parent: Notes
    6c06eb2396ec4d27bc63baf293281e7a:
      title: How Liberation and Delusion Develop Out of the Clear Light of the Ground,
        etc.
      parent: Notes
    ddde5c4ed25641908ece8cf5719ffdda:
      title: Notes from the Oral Tradition on Ālaya, Ālaya Consciousness, etc.
      parent: Notes
    4b3f5770a6b8472aaf153bd8e6083475:
      title: Dzogchen Aspiration Prayer
      parent: Prayers
    0fe5241e3ce14b59a7eb3bfae9f375fe:
      title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru
        from Afar'
      parent: Prayers
    7c6ec40900774a90ac151f065fd74849:
      title: A Dzogchen Tögal Prayer
      parent: Prayers
    66ce88050de745cd8e1e1890a421522f:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Prayers
    0831cfbea9694aee9e80e1ae7190f1d3:
      title: 'The Pure Three Kāyas Ablaze in Perfect Splendour: A Prayer Based on
        the Meaning of the Great Perfection'
      parent: Prayers
    fdcf6d320767456e8d3a7dfda42db7a5:
      title: 'Self-Radiance of Indestructible Awareness and Emptiness: An Aspiration
        towards the Meaning of the Indivisible Ground, Path and Fruition of the Great
        Perfection Mañjuśrī'
      parent: Prayers
    8fa72697ffb243be9d79c68fcd704793:
      title: Prayer to Nyala Pema Dündul
      parent: Prayers
    37da78dc366940ec90640f2845d77505:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Prayers
    b6dbb821e2a84c2db057e0fbe0386794:
      title: The Song of the Vajra
      parent: Songs
    e8cc5ac5e70645b2a2185759a423a6d4:
      title: A Song in Six Verses
      parent: Songs
    31dcfff2998c45a6938393216dfb3b39:
      title: Song of Experiential Certainty
      parent: Songs
    181a04fe1b7842d88b9968bca05d1fb3:
      title: Spontaneously Written Song of Experience
      parent: Songs
    13a6278e299f47aa8982d07ed8ed4f29:
      title: In This Pure Awareness
      parent: Songs
    53bcf36e4f6e4cf396761ea02d73fb6a:
      title: 'Aho Ye: Impressions of an Insightful Experience'
      parent: Songs
    eae84834f46b485fb29ee6b27d533daf:
      title: Five-Verse Doha of Yogic Realization
      parent: Songs
    73f9c9912fd548668f5ec35672a2094d:
      title: The Final Testament of Yukhok Chatralwa as Transmitted to Lama Rigdzin
        Nyima
      parent: Testament
created_at: '2022-03-01T03:36:31.987940'
last_modified_at: '2022-03-01T03:36:31.987946'
